fragment intferfaceL3Fragment on InfraInterfaceL3 {
  name {
    value
  }
  description {
    value
  }
  role {
    value
  }
  ip_addresses {
    edges {
      node {
        address {
          value
        }
      }
    }
  }
}
